[tool.poetry]
name = "rsa-cryptosystem"
version = "0.1.0"
description = ""
authors = ["Joonas Maisala <joonas-maisala@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pylint = "^2.12.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
coverage = "^6.3.2"
pylint = "^2.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
